### ISSUE TITLE
rules for `xor`

### ISSUE THREAD

**Issue by JeffreySarnoff** [HarrisonGrodin/Rewrite.jl#72]
include rules for `xor` (`⊻`)

do you need rules like `and(x, true) => x`, `xor(false, x) => x`, `xor(x, true) => !(x)`

**Comment by HarrisonGrodin** [comment]
It would be great to have rules for `xor`. (Would you mind if I changed the title to make that the primary focus of this issue?)

We have `and(x, true) => x` in the `BOOLEAN` rule set:
https://github.com/HarrisonGrodin/Rewrite.jl/blob/9205fd121866d9dceb60084004b0564cd2e7c942/src/rules.jl#L117-L152
Note that `&`/`|` are defined to be commutative in [algebra.jl](https://github.com/HarrisonGrodin/Rewrite.jl/blob/9205fd121866d9dceb60084004b0564cd2e7c942/src/algebra.jl#L10-L14).

**Comment by JeffreySarnoff** [comment]
I will put together a PR for this.

Would this rule be useful `xor(x, or(x, y)) => and(neg(x), y)` ?
Why do you use `neg(x)` for `not(x)`?
